language: c
branches:
  only:
  - master
  - staging
  - travis
env:
  HAXE_VER: 3.1.3
  global:
    secure: LZkP52SwAyTUUIcAPHBzzUIvr7lzB5dPW6SlRWguFaAR32bvNqBvVBoejcis6vR3Oo4e0uiOzlnkNMm/uiDHV/tTKa6Aa2onBCXyGlXw+/XX4p/KzqZuXeRggoO2OxZnoGFQUE1hbc9LgDJ9ToYlLJpqYC8u2DJiXWEMWUAk1G0=
  matrix:
  - TARGET=neko
matrix:
  fast_finish: true
before_install:
- travis_retry git clone --depth=50 --branch=master git://github.com/waneck/travis-hx.git ~/travis-hx
- openssl aes-256-cbc -k "$super_secret_password" -in deploy_key.enc -out deploy_key -d
install:
- ~/travis-hx/setup.sh
- cd $TRAVIS_BUILD_DIR
- haxelib install ufront-mvc 1.0.0-rc.11
- haxelib install compiletime 2.5.1
- haxelib install markdown 1.0.0
- haxelib install detox 1.0.0-rc.7
- haxelib install ufront-uftasks 1.0.0-beta.12
- haxelib install ufront
script:
- cd $TRAVIS_BUILD_DIR
after_success:
- haxelib run ufront deploy
- wget http://haxe.org/update/manual/
- wget http://haxe.org/update/site/
addons:
  ssh_known_hosts: haxe.org
