# example travis.yml haxe configuration
language: c # change this to objective-c to test on a mac machine

# Based on instructions from:
# http://pghalliday.com/github/ssh/travis-ci/2014/09/19/auto-build-and-deploy-github-pages-with-travis-ci.html

branches:
  only:
    - master
    - staging
    - travis

env:
  HAXE_VER: 3.1.3
  #  - unset/empty or "latest": get latest from hxbuilds
  #  - 3.1.3 or 3.1.2: get them from hxbuilds
  #  - other: build from git
  global:
  matrix:
    - TARGET=neko 
      # optional: FILENAME

matrix:
  fast_finish: true

before_install: # clone travis-hx repo
  - travis_retry git clone --depth=50 --branch=master git://github.com/waneck/travis-hx.git ~/travis-hx
  - openssl aes-256-cbc -K $encrypted_c7c1240b42e4_key -iv $encrypted_c7c1240b42e4_iv -in deploy_key.enc -out deploy_key -d
  - chmod 600 deploy_key
  - eval `ssh-agent -s`
  - ssh-add deploy_key
  - git config --global user.name "$GIT_NAME"
  - git config --global user.email "$GIT_EMAIL"

install: # setup the target
  - ~/travis-hx/setup.sh
  - cd $TRAVIS_BUILD_DIR
  #- haxelib install all
  - haxelib install ufront-mvc 1.0.0-rc.11
  - haxelib install compiletime 2.5.1
  - haxelib install markdown 1.0.0
  - haxelib install detox 1.0.0-rc.7
  - haxelib install ufront-uftasks 1.0.0-beta.12
  - haxelib install ufront

script:
  - cd $TRAVIS_BUILD_DIR
  # build the target. This will call haxe with the HXFLAGS and HXFLAGS_EXTRA environment variables
  #- HXFLAGS="-cp src -main test.TestAll" ~/travis-hx/build.sh
  # run the tests
  #- ~/travis-hx/runtests.sh $FILENAME # this will set the $FILENAME defined on the environment variable to run the tests

after_success:
  - haxelib run ufront deploy
  - wget http://haxe.org/update/manual/
  - wget http://haxe.org/update/site/

addons:
  ssh_known_hosts: haxe.org

